Feature: About Sample # features/about.feature:1

  Scenario: Transaction Processing                           # features/about.feature:3
    Given Sample Database                                    # features/steps/about.py:9
    When Transactions are submitted                          # features/steps/about.py:13
    Then Enforce business policies with Logic (rules + code) # features/steps/about.py:17

Feature: Application Integration # features/api.feature:1

  Scenario: GET Customer          # features/api.feature:3
    Given Customer Account: VINET # features/steps/api.py:9
    When GET Orders API           # features/steps/api.py:13
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/api.py", line 20, in step_impl
          r = requests.get(url=get_order_uri, headers= test_utils.login())
                                                       ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    Then VINET retrieved          # None

  Scenario: GET Department                      # features/api.feature:9
    Given Department 2                          # features/steps/api.py:31
    When GET Department with SubDepartments API # features/steps/api.py:35
    Then SubDepartments returned                # features/steps/api.py:39
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/api.py", line 44, in step_impl
          r = requests.get(url=get_dept_uri, headers= test_utils.login())
                                                      ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>


Feature: Place Order # features/place_order.feature:1

  Scenario: Good Order Custom Service                  # features/place_order.feature:3
    Given Customer Account: ALFKI                      # features/steps/place_order.py:48
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/place_order.py", line 50, in step_impl
          alfki_before = get_ALFLI()
                         ^^^^^^^^^^^
        File "features/steps/place_order.py", line 24, in get_ALFLI
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    When Good Order Placed                             # None
    Then Logic adjusts Balance (demo: chain up)        # None
    Then Logic adjusts Products Reordered              # None
    Then Logic sends email to salesrep                 # None
    Then Logic adjusts aggregates down on delete order # None

  Scenario: Bad Order Custom Service          # features/place_order.feature:12
    Given Customer Account: ALFKI             # features/steps/place_order.py:48
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/place_order.py", line 50, in step_impl
          alfki_before = get_ALFLI()
                         ^^^^^^^^^^^
        File "features/steps/place_order.py", line 24, in get_ALFLI
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    When Order Placed with excessive quantity # None
    Then Rejected per Check Credit            # None

  Scenario: Alter Item Qty to exceed credit      # features/place_order.feature:18
    Given Customer Account: ALFKI                # features/steps/place_order.py:48
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/place_order.py", line 50, in step_impl
          alfki_before = get_ALFLI()
                         ^^^^^^^^^^^
        File "features/steps/place_order.py", line 24, in get_ALFLI
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    When Order Detail Quantity altered very high # None
    Then Rejected per Check Credit               # None

  Scenario: Alter Required Date - adjust logic pruned  # features/place_order.feature:24
    Given Customer Account: ALFKI                      # features/steps/place_order.py:48
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/place_order.py", line 50, in step_impl
          alfki_before = get_ALFLI()
                         ^^^^^^^^^^^
        File "features/steps/place_order.py", line 24, in get_ALFLI
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    When Order RequiredDate altered (2013-10-13)       # None
    Then Balance not adjusted                          # None

  Scenario: Set Shipped - adjust logic reuse    # features/place_order.feature:30
    Given Customer Account: ALFKI               # features/steps/place_order.py:48
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/place_order.py", line 50, in step_impl
          alfki_before = get_ALFLI()
                         ^^^^^^^^^^^
        File "features/steps/place_order.py", line 24, in get_ALFLI
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    When Order ShippedDate altered (2013-10-13) # None
    Then Balance reduced 1086                   # None

  Scenario: Reset Shipped - adjust logic reuse  # features/place_order.feature:36
    Given Shipped Order                         # features/steps/place_order.py:337
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/place_order.py", line 339, in step_impl
          context.alfki_shipped = get_ALFLI()
                                  ^^^^^^^^^^^
        File "features/steps/place_order.py", line 24, in get_ALFLI
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    When Order ShippedDate set to None          # None
    Then Logic adjusts Balance by -1086         # None

  Scenario: Clone Existing Order              # features/place_order.feature:42
    Given Shipped Order                       # features/steps/place_order.py:337
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/place_order.py", line 339, in step_impl
          context.alfki_shipped = get_ALFLI()
                                  ^^^^^^^^^^^
        File "features/steps/place_order.py", line 24, in get_ALFLI
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    When Cloning Existing Order               # None
    Then Logic Copies ClonedFrom OrderDetails # None

Feature: Salary Change # features/salary_change.feature:1

  Scenario: Audit Salary Change              # features/salary_change.feature:3
    Given Employee 5 (Buchanan) - Salary 95k # features/steps/salary_change.py:9
    When Patch Salary to 200k                # features/steps/salary_change.py:13
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/salary_change.py", line 42, in step_impl
          r = requests.patch(url=patch_emp_uri, json=patch_args, headers= test_utils.login())
                                                                          ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    Then Salary_audit row created            # None

  Scenario: Manage ProperSalary              # features/salary_change.feature:8
    Given Employee 5 (Buchanan) - Salary 95k # features/steps/salary_change.py:9
    When Retrieve Employee Row               # features/steps/salary_change.py:106
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/salary_change.py", line 116, in step_impl
          header = test_utils.login()
                   ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    Then Verify Contains ProperSalary        # None

  Scenario: Raise Must be Meaningful         # features/salary_change.feature:13
    Given Employee 5 (Buchanan) - Salary 95k # features/steps/salary_change.py:9
    When Patch Salary to 96k                 # features/steps/salary_change.py:76
      Traceback (most recent call last):
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/model.py", line 1329, in run
          match.run(runner.context)
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/venv/lib/python3.11/site-packages/behave/matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features/steps/salary_change.py", line 96, in step_impl
          r = requests.patch(url=patch_emp_uri, json=patch_args, headers= test_utils.login())
                                                                          ^^^^^^^^^^^^^^^^^^
        File "/Users/val/dev/fiddle/safrs310/safrs_310_rc2/test/api_logic_server_behave/features/steps/test_utils.py", line 44, in login
          raise Exception(f'POST login failed with {r.text}')
      Exception: POST login failed with <!doctype html>
      <html lang=en>
      <title>500 Internal Server Error</title>
      <h1>Internal Server Error</h1>
      <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

    Then Reject - Raise too small            # None

&nbsp;&nbsp;
Completed at May 31, 2023 13:00:45